[versions]
springBoot = "4.0.2"
springJcef = "0.10.37"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm",  version = "2.3.0" }

[libraries]
plugin-dependencyManagement = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version     = "1.1.7"      }
plugin-springBoot           = { module = "org.springframework.boot:spring-boot-gradle-plugin",                            version.ref = "springBoot" }
springJcef                  = { module = "io.github.bitfist:jcef-spring-boot-starter",                                    version.ref = "springJcef" }
test-junit5Bom              = { module = "org.junit:junit-bom",                                                           version     = "6.0.2"     }
